### ISSUE TITLE
remote: Problem with remote controll layout in Firefox Mobile

### ISSUE THREAD

**Issue by Eccenux** [deckgo/deckdeckgo#752]
### Affected part of DeckDeckGo
- [x] Remote control

### Reproduction

Steps to reproduce:
1. Create/open a presentation
2. Share.
3. Open with Firefox on Android.
 
### Expected Behavior

I should see Next/Previous buttons in full.

### Actual Behavior

Buttons are cut off
<img src="https://user-images.githubusercontent.com/1045235/83364209-f6904900-a39f-11ea-90a5-d3b5adad1abf.png" width="200" alt="cut off buttons" />

Here is a full page screen (scrolled-screen):
<img src="https://user-images.githubusercontent.com/1045235/83364393-5affd800-a3a1-11ea-8821-6c38bf013aa8.png" width="200" alt="buttons cut in two" />

Note that you should be able to use a vh-calc trick to avoid this problem cross-browser:
https://css-tricks.com/the-trick-to-viewport-units-on-mobile/

### Environment

- Browser(s): Firefox for Android
- Operating System (e.g. Windows, macOS, Ubuntu): Android.

**Comment by peterpeterparker** [comment]
Which version of Firefox are you  using?

I'm using  v76 and I don't face such issues.

<img width="767" alt="Capture d’écran 2020-06-01 à 07 47 11" src="https://user-images.githubusercontent.com/16886711/83379623-4bea4b80-a3dc-11ea-9645-e4ea2c2c0ab5.png">
<img width="767" alt="Capture d’écran 2020-06-01 à 07 47 15" src="https://user-images.githubusercontent.com/16886711/83379632-50aeff80-a3dc-11ea-9852-100c24a7ea40.png">

**Comment by Eccenux** [comment]
You are using desktop Firefox. Firefox on Android (mobile) is not the same thing. I use latest Firefox on Android. Note that this is probably an issue with hiding the address bar which is only a thing on mobile.  
  
Also note that Firefox on and iPhone (as all other browsers) is just Safari based webview. So you can only really test on Android.

**Comment by peterpeterparker** [comment]
Thx for the feedback, Firefox Mobile only, well noted.

Can you provide a PR?

**Comment by Eccenux** [comment]
I didn't found any clear instructions on how to build the whole project... But I was able to figure out some details in devtools.

Note that you should also get nicer layout for Chrome too.  
  
I think the \`app-remote\` needs some re-structuring:

1.  In `main` add a container with a class \`.deck-container\`.
2.  Put prev/next directly in the container (after .deck).
3.  Be sure that app-notes is outside of the container.
4.  Apply style changes (notice \``height: calc(100% - 8px)`\`).
5.  You might need to tweak some layouts inside the button.

That last 8px is crucial because animations for the buttons makes them bigger and this seem to mess-up layouts.

Style changes:

```css
app-remote main.connected {
  	/* display: grid; */
  	/* grid-template-rows: calc((100% - 64px) / 2) calc((100% - 64px) / 2) 64px; */
}
app-remote main.connected div.deck {
  	margin-bottom: 0px;
}

.deck-container {
  	display: grid;
  	grid-template-columns: 1fr 1fr;
  	grid-template-areas: 
  		"deck deck" 
  		"prev next"
  	;
  	grid-template-rows: 1fr 1fr;
  	height: calc(100% - 70px);
  	grid-gap: 1em;
}

.deck {
  	grid-area: deck;
}
.deck-navigation-button-prev {
  	grid-area: prev;
  	padding-left: 1em;
}
.deck-navigation-button-next {
  	grid-area: next;
  	padding-right: 1em;
}
.deck-navigation-button-prev ion-button,
.deck-navigation-button-next ion-button {
	height: calc(100% - 8px);
	width: 100%;
	box-sizing: border-box;
}
```

After similar changes in WebIDE I got something like this (purple lines show the new grid):

![](https://user-images.githubusercontent.com/1045235/83578828-ff1b8780-a537-11ea-8dd0-8cacaea53349.png)
